export const CONSULTING_TYPE_LIST_REQUEST = "CONSULTING_TYPE_LIST_REQUEST";
export const CONSULTING_TYPE_LIST_SUCCESS = "CONSULTING_TYPE_LIST_SUCCESS";
export const CONSULTING_TYPE_LIST_FAIL = "CONSULTING_TYPE_LIST_FAIL";

export const CONSULTING_TYPE_DETAILS_REQUEST = "CONSULTING_TYPE_DETAILS_REQUEST";
export const CONSULTING_TYPE_DETAILS_SUCCESS = "CONSULTING_TYPE_DETAILS_SUCCESS";
export const CONSULTING_TYPE_DETAILS_FAIL = "CONSULTING_TYPE_DETAILS_FAIL";

export const CONSULTING_TYPE_SAVE_REQUEST = "CONSULTING_TYPE_SAVE_REQUEST";
export const CONSULTING_TYPE_SAVE_SUCCESS = "CONSULTING_TYPE_SAVE_SUCCESS";
export const CONSULTING_TYPE_SAVE_FAIL = "CONSULTING_TYPE_SAVE_FAIL";

export const CONSULTING_TYPE_DELETE_REQUEST = "CONSULTING_TYPE_DELETE_REQUEST";
export const CONSULTING_TYPE_DELETE_SUCCESS = "CONSULTING_TYPE_DELETE_SUCCESS";
export const CONSULTING_TYPE_DELETE_FAIL = "CONSULTING_TYPE_DELETE_FAIL";

  