export const CONSULTANCY_REPORT_LIST_REQUEST = "CONSULTANCY_REPORT_LIST_REQUEST";
export const CONSULTANCY_REPORT_LIST_SUCCESS = "CONSULTANCY_REPORT_LIST_SUCCESS";
export const CONSULTANCY_REPORT_LIST_FAIL = "CONSULTANCY_REPORT_LIST_FAIL";