

export const COURSE_AVAILABILITY_DATE_SAVE_REQUEST = "COURSE_AVAILABILITY_DATE_SAVE_REQUEST";
export const COURSE_AVAILABILITY_DATE_SAVE_SUCCESS = "COURSE_AVAILABILITY_DATE_SAVE_SUCCESS";
export const COURSE_AVAILABILITY_DATE_SAVE_FAIL = "COURSE_AVAILABILITY_DATE_SAVE_FAIL";
