export const COURSE_BENEFIT_LIST_REQUEST = "COURSE_BENEFIT_LIST_REQUEST";
export const COURSE_BENEFIT_LIST_SUCCESS = "COURSE_BENEFIT_LIST_SUCCESS";
export const COURSE_BENEFIT_LIST_FAIL = "COURSE_BENEFIT_LIST_FAIL";

export const COURSE_BENEFIT_DETAILS_REQUEST = "COURSE_BENEFIT_DETAILS_REQUEST";
export const COURSE_BENEFIT_DETAILS_SUCCESS = "COURSE_BENEFIT_DETAILS_SUCCESS";
export const COURSE_BENEFIT_DETAILS_FAIL = "COURSE_BENEFIT_DETAILS_FAIL";

export const COURSE_BENEFIT_SAVE_REQUEST = "COURSE_BENEFIT_SAVE_REQUEST";
export const COURSE_BENEFIT_SAVE_SUCCESS = "COURSE_BENEFIT_SAVE_SUCCESS";
export const COURSE_BENEFIT_SAVE_FAIL = "COURSE_BENEFIT_SAVE_FAIL";

export const COURSE_BENEFIT_DELETE_REQUEST = "COURSE_BENEFIT_DELETE_REQUEST";
export const COURSE_BENEFIT_DELETE_SUCCESS = "COURSE_BENEFIT_DELETE_SUCCESS";
export const COURSE_BENEFIT_DELETE_FAIL = "COURSE_BENEFIT_DELETE_FAIL";

  