

export const CTA_PAYMENT_SAVE_REQUEST = "CTA_PAYMENT_SAVE_REQUEST";
export const CTA_PAYMENT_SAVE_SUCCESS = "CTA_PAYMENT_SAVE_SUCCESS";
export const CTA_PAYMENT_SAVE_FAIL = "CTA_PAYMENT_SAVE_FAIL";

