export const RESOURCE_LIST_REQUEST = "RESOURCE_LIST_REQUEST";
export const RESOURCE_LIST_SUCCESS = "RESOURCE_LIST_SUCCESS";
export const RESOURCE_LIST_FAIL = "RESOURCE_LIST_FAIL";

export const RESOURCE_DETAILS_REQUEST = "RESOURCE_DETAILS_REQUEST";
export const RESOURCE_DETAILS_SUCCESS = "RESOURCE_DETAILS_SUCCESS";
export const RESOURCE_DETAILS_FAIL = "RESOURCE_DETAILS_FAIL";

export const RESOURCE_SAVE_REQUEST = "RESOURCE_SAVE_REQUEST";
export const RESOURCE_SAVE_SUCCESS = "RESOURCE_SAVE_SUCCESS";
export const RESOURCE_SAVE_FAIL = "RESOURCE_SAVE_FAIL";

export const RESOURCE_DELETE_REQUEST = "RESOURCE_DELETE_REQUEST";
export const RESOURCE_DELETE_SUCCESS = "RESOURCE_DELETE_SUCCESS";
export const RESOURCE_DELETE_FAIL = "RESOURCE_DELETE_FAIL";

  