
export const SOFTWARE_TRAINING_PRICE_LIST_REQUEST = "SOFTWARE_TRAINING_PRICE_LIST_REQUEST";
export const SOFTWARE_TRAINING_PRICE_LIST_SUCCESS = "SOFTWARE_TRAINING_PRICE_LIST_SUCCESS";
export const SOFTWARE_TRAINING_PRICE_LIST_FAIL = "SOFTWARE_TRAINING_PRICE_LIST_FAIL";

export const SOFTWARE_TRAINING_PRICE_DETAILS_REQUEST = "SOFTWARE_TRAINING_PRICE_DETAILS_REQUEST";
export const SOFTWARE_TRAINING_PRICE_DETAILS_SUCCESS = "SOFTWARE_TRAINING_PRICE_DETAILS_SUCCESS";
export const SOFTWARE_TRAINING_PRICE_DETAILS_FAIL = "SOFTWARE_TRAINING_PRICE_DETAILS_FAIL";

export const SOFTWARE_TRAINING_PRICE_SAVE_REQUEST = "SOFTWARE_TRAINING_PRICE_SAVE_REQUEST";
export const SOFTWARE_TRAINING_PRICE_SAVE_SUCCESS = "SOFTWARE_TRAINING_PRICE_SAVE_SUCCESS";
export const SOFTWARE_TRAINING_PRICE_SAVE_FAIL = "SOFTWARE_TRAINING_PRICE_SAVE_FAIL";

export const SOFTWARE_TRAINING_PRICE_DELETE_REQUEST = "SOFTWARE_TRAINING_PRICE_DELETE_REQUEST";
export const SOFTWARE_TRAINING_PRICE_DELETE_SUCCESS = "SOFTWARE_TRAINING_PRICE_DELETE_SUCCESS";
export const SOFTWARE_TRAINING_PRICE_DELETE_FAIL = "SOFTWARE_TRAINING_PRICE_DELETE_FAIL";

