export const TESTIMONIAL_DETAIL_LIST_REQUEST = "TESTIMONIAL_DETAIL_LIST_REQUEST";
export const TESTIMONIAL_DETAIL_LIST_SUCCESS = "TESTIMONIAL_DETAIL_LIST_SUCCESS";
export const TESTIMONIAL_DETAIL_LIST_FAIL = "TESTIMONIAL_DETAIL_LIST_FAIL";

export const TESTIMONIAL_DETAIL_DETAILS_REQUEST = "TESTIMONIAL_DETAIL_DETAILS_REQUEST";
export const TESTIMONIAL_DETAIL_DETAILS_SUCCESS = "TESTIMONIAL_DETAIL_DETAILS_SUCCESS";
export const TESTIMONIAL_DETAIL_DETAILS_FAIL = "TESTIMONIAL_DETAIL_DETAILS_FAIL";

export const TESTIMONIAL_DETAIL_SAVE_REQUEST = "TESTIMONIAL_DETAIL_SAVE_REQUEST";
export const TESTIMONIAL_DETAIL_SAVE_SUCCESS = "TESTIMONIAL_DETAIL_SAVE_SUCCESS";
export const TESTIMONIAL_DETAIL_SAVE_FAIL = "TESTIMONIAL_DETAIL_SAVE_FAIL";

export const TESTIMONIAL_DETAIL_DELETE_REQUEST = "TESTIMONIAL_DETAIL_DELETE_REQUEST";
export const TESTIMONIAL_DETAIL_DELETE_SUCCESS = "TESTIMONIAL_DETAIL_DELETE_SUCCESS";
export const TESTIMONIAL_DETAIL_DELETE_FAIL = "TESTIMONIAL_DETAIL_DELETE_FAIL";

  