export const UNIQUE_SOLUTION_DETAIL_LIST_REQUEST = "UNIQUE_SOLUTION_DETAIL_LIST_REQUEST";
export const UNIQUE_SOLUTION_DETAIL_LIST_SUCCESS = "UNIQUE_SOLUTION_DETAIL_LIST_SUCCESS";
export const UNIQUE_SOLUTION_DETAIL_LIST_FAIL = "UNIQUE_SOLUTION_DETAIL_LIST_FAIL";

export const UNIQUE_SOLUTION_DETAIL_DETAILS_REQUEST = "UNIQUE_SOLUTION_DETAIL_DETAILS_REQUEST";
export const UNIQUE_SOLUTION_DETAIL_DETAILS_SUCCESS = "UNIQUE_SOLUTION_DETAIL_DETAILS_SUCCESS";
export const UNIQUE_SOLUTION_DETAIL_DETAILS_FAIL = "UNIQUE_SOLUTION_DETAIL_DETAILS_FAIL";

export const UNIQUE_SOLUTION_DETAIL_SAVE_REQUEST = "UNIQUE_SOLUTION_DETAIL_SAVE_REQUEST";
export const UNIQUE_SOLUTION_DETAIL_SAVE_SUCCESS = "UNIQUE_SOLUTION_DETAIL_SAVE_SUCCESS";
export const UNIQUE_SOLUTION_DETAIL_SAVE_FAIL = "UNIQUE_SOLUTION_DETAIL_SAVE_FAIL";

export const UNIQUE_SOLUTION_DETAIL_DELETE_REQUEST = "UNIQUE_SOLUTION_DETAIL_DELETE_REQUEST";
export const UNIQUE_SOLUTION_DETAIL_DELETE_SUCCESS = "UNIQUE_SOLUTION_DETAIL_DELETE_SUCCESS";
export const UNIQUE_SOLUTION_DETAIL_DELETE_FAIL = "UNIQUE_SOLUTION_DETAIL_DELETE_FAIL";

  